name: adzy-workbench
networks:
  adzy_adzy-network:
    external: true
    name: adzy_adzy-network
services:
  adzy-workbench:
    container_name: "adzy-workbench-container"
    image: "adzy-workbench-image"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: dev
      DB_HOST: adzy-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: adzy_dev
    networks:
      - adzy_adzy-network